---
- name: add-EPG
  hosts: all
  gather_facts: false
 
  tasks:
   - name: Add a new EPG
     cisco.aci.aci_epg:
       host: apic
       username: admin
       password: SomeSecretPassword
       tenant: production
       ap: intranet
       epg: web_epg
       description: Web Intranet EPG
       bd: prod_bd
       monitoring_policy: default
       preferred_group: yes
       state: present
     delegate_to: localhost
