---
- name: add-EPG
  hosts: localhost
  gather_facts: false
 
  tasks:
   - name: Add a new EPG
     cisco.aci.aci_epg:
       host: sandboxapicdc.cisco.com
       username: admin
       password: ciscopsdt
       validate_certs: false
       tenant: ATEST
       ap: ATEST
       epg: "VLAN_{{ item }}"
       description: TEST-EPG
       bd: ATEST
       monitoring_policy: default
       preferred_group: yes
       state: present
     delegate_to: localhost
     loop:
       - 110
       - 120
       - 130
       - 140
       - 150
       - 160
       - 170
       - 180
       - 190
       - 200
