---
- name: add-EPG
  hosts: localhost
  gather_facts: false
 
  tasks:
   - name: Add a new EPG
     cisco.aci.aci_epg:
       host: sandboxapicdc.cisco.com
       username: admin
       password: ciscopsdt
       validate_certs: false
       tenant: ATEST
       ap: ATEST
       epg: VLAN_110
       description: TEST-EPG
       bd: ATEST
       monitoring_policy: default
       preferred_group: yes
       state: present
     delegate_to: localhost
