---
- name: test
  hosts: localhost
  gather_facts: false
  connection: local
 
  tasks:
   - name: Query all tenants
     cisco.aci.aci_tenant:
       host: sandboxapicdc.cisco.com
       username: admin
       password: ciscopsdt
       state: query
       validate_certs: false
       output_level: debug
     delegate_to: localhost
     register: query_result
    
   - name: Print returned json dictionary
      debug:
        var: query_result
#   - debug:
#       msg: "{{results}}"
