---
- name: Add a static port to EPGs
  hosts: localhost
  gather_facts: false
 
  tasks:
   - name: Add a static port to EPGs
     cisco.aci.aci_static_binding_to_epg:
       host: sandboxapicdc.cisco.com
       username: admin
       password: ciscopsdt
       validate_certs: false
       ap: ATEST
       tenant: ATEST
       epg: "VLAN_{{ item }}"
       encap_id: "{{ item }}"
       deploy_immediacy: lazy
       interface_mode: trunk
       interface_type: switch_port
       pod_id: 1
       leafs: 102
       interface: '1/7'
       state: present
     delegate_to: localhost
     loop:
       - 110
       - 120
       - 130
       - 140
       - 150
       - 160
       - 170
       - 180
       - 190
       - 200
